### ISSUE TITLE
Write L1DS Destreaking and Cosmic Ray Despiking Module

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/punchbowl#12]
# Destreak and despike

## Tasks
- [x] settle on despiking algorithm and implement
- [x] settle on destreaking algorithm and implement
- [ ] test despiking algorithm on SUVI L1b data
- [ ] make destreaking pull parameters from metadata
- [ ] update in flow run
- [ ] test on some fake data with spikes and streaks

## Description

Module L1DS scrubs input datasets of cosmic-ray, or similar, transients from the dataset, and de-streaks input data by applying the PSF/Inverse PSF, it flags missing data in the output metadata HDU.

De-spiking scrubs cosmic ray hits from the charge-coupled device (CCD) images. This is done before de-streaking, to minimize artifacts from individual cosmic rays. Individual PUNCH images contain vertical (in the detector coordinate system) streaks due to the shutterless frame-transfer (See, for example, Iglesias F.A. (2015) and references therein) operating mode: the CCD continues to expose as the image is migrated to the storage portion of the CCD. Cosmic rays are single events and do not generate column-aligned streaks, while stars are stationary and do. De-spiking uses a convolution with a custom “spike detection” mask tuned to the camera readout mode. The spike detection mask is directly convolved with the photometric intermediate image to produce a spike-detection image, which in turn is thresholded to produce a spike mask. The spike mask identifies spike pixels, which are replaced with a median of nearby non-spiked pixels in the same detector row, prior to de-streaking. The spike detection mask and the de-streaking kernel are closely related and are produced at the same time pre-flight and validated during commissioning. The technique exploits non-streaking of spikes (see PUNCH Science Data Management Plan (23103-SDMP) §4.4.2.2-3).

De-streaking accounts for smearing effects from the PUNCH shutterless frame transfer mode of operation. Each detector continues exposing during readout as the science image is moved off of the active detector area and onto the storage area. This convolves the resulting image with a causal “effective PSF”. that comprises a spike and a long, constant-value tail. The value of the tail depends on the ratio between the camera exposure time and the per-row transfer time. The tail is not subject to the same flat-field operation as normal photometric pixels, because the same physical detector records all of the electrons in the tail, as the image is transferred past an illuminated pixel.

The De-streaking Module convolves the image with the calculated inverse PSF (e.g., DeForest, C. E. (2009), Poduval, B. (2013)). This follows the method used successfully with Solar Terrestrial Relations Observatory (STEREO)/Heliographic Imager (HI) data which exhibited 10× stronger streaking than PUNCH. The streak PSF and its inverse PSF are calculated a priori for each individual exposure time and method, and verified with flight data. After de-streaking, spike pixels are marked missing in the secondary HDU.

## work log
- @jmbhughes : ? hours
- @sakovac : ? hours
