### ISSUE TITLE
Optimize reprojection to polar coordinates

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/punchbowl#79]
We need to determine the correct dimensions to scale into polar coordinates. For example, if we compress the polar axis too much, it will result in poor sampling when reprojecting back to cartesian. 

## tasks
- [ ] make a simple test dataset (maybe all ones?) to reproject and test
- [ ] do the forward and backward reprojections on a variety of scales
- [ ] decide what worked best

## work log
- @lowderchris : 2 hours
