### ISSUE TITLE
Finalize Level 0 pipeline segment

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/punchbowl#90]
# Finalize Level 0 pipeline segment

Create a final level 0 pipeline segment

## Tasks 
- [ ] write the initial level 0 decoder in punchbowl
- [ ] automate with databases in punchpipe
- [ ] thoroughly test
- [ ] document the design

## Work log:
- @jmbhughes : ? hours

**Comment by jmbhughes** [comment]
Done.
